name: "Publish DevContainer Features"

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "metadata.json"

jobs:
  publish-features:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"
